ALTER TABLE CUSTOMERDETAIL 
DROP CONSTRAINT SYS_C004430;

ALTER TABLE CUSTOMERDETAIL 
ADD (IDKEY NUMBER NOT NULL);

ALTER TABLE CUSTOMERDETAIL  
MODIFY (INVOICE_DATE VARCHAR2(20) );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (BILLEDNAME VARCHAR2(200 BYTE) );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (BILLEDADDRESS VARCHAR2(250 BYTE) );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (CHALLAN_NO_DATE VARCHAR2(20) );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (PO_NO_DATE VARCHAR2(20) );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (GRAND_TOTAL_WORDS VARCHAR2(200 BYTE) );

ALTER TABLE CUSTOMERDETAIL
ADD CONSTRAINT SYS_C004430 PRIMARY KEY 
(
  IDKEY 
)
ENABLE;
--------------------------

ALTER TABLE DESPATCH_DETAIL 
RENAME TO DISPATCH_DETAIL;

ALTER TABLE DISPATCH_DETAIL  
MODIFY (PER_RR_MM_NO_DATE VARCHAR2(20) );

ALTER TABLE DISPATCH_DETAIL  
MODIFY (BL_NO_DATE VARCHAR2(20) );

ALTER TABLE DISPATCH_DETAIL  
MODIFY (DOCUMENT_THRU_BANK VARCHAR2(100 BYTE) );

ALTER TABLE DISPATCH_DETAIL  
MODIFY (BY_MOTOR_TRASPORT VARCHAR2(100 BYTE) );
---------------------------

ALTER TABLE PRODUCT_PER_CUSTOMER  
MODIFY (PARTICULARS_PRODUCT VARCHAR2(100 BYTE) );

--------------------------

alter table customerdetail add constraint INVOICE_UNIQUE_CONST UNIQUE(INVOICENO);

alter table DISPATCH_DETAIL add constraint INVOICE_UNIQUE_2_CONST UNIQUE(INVOICENO);

