ALTER TABLE CUSTOMERDETAIL  
MODIFY (INVOICE_DATE DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (BILLEDNAME DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (BILLEDADDRESS DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (VAT_NO DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (CHALLAN_NO DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (CHALLAN_NO_DATE DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (PO_NO DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (PO_NO_DATE DEFAULT '' );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (COURIER_CHARGE DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (LBT DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (VAT DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (SERVICE_TAX DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (LBT_PERCENT DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (VAT_PERCENT DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (SERVICE_TAX_PERCENT DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (GRAND_TOTAL DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (GREAT_GRAND_TOTAL DEFAULT 0 );

ALTER TABLE CUSTOMERDETAIL  
MODIFY (GRAND_TOTAL_WORDS DEFAULT '' );