
  CREATE TABLE USERDETAIL
  (	"IDKEY" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"EMAILID" VARCHAR2(50 BYTE), 
	 CONSTRAINT "USERDETAIL_PK" PRIMARY KEY ("IDKEY"));
	 
	 -------------------------------
	 CREATE SEQUENCE USERDETAIL_SEQ  
	 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
 