
CREATE TABLE "CUSTOMERDETAIL" 
   (	"INVOICENO" NUMBER NOT NULL ENABLE, 
	"INVOICE_DATE" VARCHAR2(20 BYTE), 
	"BILLEDNAME" VARCHAR2(75 BYTE), 
	"BILLEDADDRESS" VARCHAR2(75 BYTE), 
	"VAT_NO" VARCHAR2(75 BYTE), 
	"CHALLAN_NO" VARCHAR2(75 BYTE), 
	"CHALLAN_NO_DATE" VARCHAR2(20 BYTE), 
	"PO_NO" VARCHAR2(75 BYTE), 
	"PO_NO_DATE" VARCHAR2(20 BYTE), 
	"COURIER_CHARGE" NUMBER, 
	"LBT" NUMBER, 
	"VAT" NUMBER, 
	"SERVICE_TAX" NUMBER, 
	"LBT_PERCENT" NUMBER, 
	"VAT_PERCENT" NUMBER, 
	"SERVICE_TAX_PERCENT" NUMBER, 
	"GRAND_TOTAL" NUMBER, 
	"GREAT_GRAND_TOTAL" NUMBER, 
	"GRAND_TOTAL_WORDS" VARCHAR2(75 BYTE), 
	"IDKEY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C007085" PRIMARY KEY ("IDKEY");
	 

	 
	 
	 
CREATE TABLE "INVOICE"."DISPATCH_DETAIL" 
   (	"IDKEY_DESPATCH" NUMBER NOT NULL ENABLE, 
	"PER_RR_MM_NO" VARCHAR2(75 BYTE), 
	"PER_RR_MM_NO_DATE" VARCHAR2(20 BYTE), 
	"BL_NO" VARCHAR2(75 BYTE), 
	"BL_NO_DATE" VARCHAR2(20 BYTE), 
	"DOCUMENT_THRU_BANK" VARCHAR2(75 BYTE), 
	"BY_MOTOR_TRASPORT" VARCHAR2(75 BYTE), 
	"INVOICENO" NUMBER, 
	"DESPATCH_TO" VARCHAR2(75 BYTE), 
	 PRIMARY KEY ("IDKEY_DESPATCH");
	 
	 
CREATE TABLE "INVOICE"."PRODUCT_PER_CUSTOMER" 
   (	"IDKEY_PPC" NUMBER NOT NULL ENABLE, 
	"INVOICENO" NUMBER, 
	"PARTICULARS_PRODUCT" VARCHAR2(75 BYTE), 
	"QUANTITY" NUMBER, 
	"RATE" NUMBER, 
	"PER" VARCHAR2(75 BYTE), 
	"AMOUNT" NUMBER, 
	 PRIMARY KEY ("IDKEY_PPC");
	 
	 
	 
	 
CREATE TABLE "INVOICE"."USERDETAIL" 
   (	"IDKEY" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"EMAILID" VARCHAR2(50 BYTE), 
	 CONSTRAINT "USERDETAIL_PK" PRIMARY KEY ("IDKEY");
	 
alter table customerdetail add constraint INVOICE_UNIQUE_CONST UNIQUE(INVOICENO);

alter table DISPATCH_DETAIL add constraint INVOICE_UNIQUE_2_CONST UNIQUE(INVOICENO);


